apiVersion: v2
name: kube-vip
version: 0 # Inherited from the VERSION file when make is run
dependencies:
- name: kube-vip
  condition: kube-vip.enabled
  version: 0.9.9
  repository: https://kube-vip.github.io/helm-charts
annotations:
  publish-repository: oci://ghcr.io/fairport-io
