{{- $bifrost := index .Values "bifrost" -}}
{{- if and $bifrost.enabled $bifrost.postgresql.external.enabled }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $bifrost.postgresql.external.existingSecret) | default dict }}
{{- $existingData := (get $existingSecret "data") | default dict }}
{{- $password := randAlphaNum 32 }}
{{- if $existingData.password }}
  {{- $password = (index $existingData "password") | b64dec }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $bifrost.postgresql.external.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: bifrost
type: Opaque
stringData:
  {{ $bifrost.postgresql.external.passwordKey }}: {{ $password }}
{{- end }}
