---
apiVersion: v2
name: fairport
version: 0 # Inherited from the VERSION file when make is run
#dependencies:
# kueue/slinky
# ingress-nginx
# Gittea
# FP Operator
# Postgres
# Kubevirt
# vCluster
# Litellm
annotations:
  publish-repository: oci://gcr.io/fairport-io
