---
apiVersion: v2
name: monitoring
version: 0 # Inherited from the VERSION file when make is run
dependencies:
- name: kube-prometheus-stack
  condition: kube-prometheus-stack.enabled
  version: 85.3.3
  repository: oci://ghcr.io/prometheus-community/charts
- name: victoria-logs-cluster
  condition: victoria-logs-cluster.enabled
  version: 0.1.5
  repository: oci://ghcr.io/victoriametrics/helm-charts
- name: victoria-traces-cluster
  condition: victoria-traces-cluster.enabled
  version: 0.1.3
  repository: oci://ghcr.io/victoriametrics/helm-charts
annotations:
  publish-repository: oci://gcr.io/fairport-io
