{{- $mpiOperator := index .Values "mpi-operator" -}}
{{- if $mpiOperator.enabled }}
{{- if $mpiOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $mpiOperator.serviceAccount.name }}
  labels:
    app: mpi-operator
    app.kubernetes.io/component: mpijob
    app.kubernetes.io/name: mpi-operator
{{- end }}
{{- end }}

