{{- $fairportUi := index .Values "fairport-ui" -}}
{{- if and $fairportUi.enabled $fairportUi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fairport-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml $fairportUi.labels | nindent 4 }}
  {{- with $fairportUi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $fairportUi.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  {{- range $fairportUi.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: fairport-ui
            port:
              name: http
      {{- end }}
  {{- end }}
  {{- with $fairportUi.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
