{{- $fairportUi := index .Values "fairport-ui" -}}
{{- if $fairportUi.enabled }}
{{- if $fairportUi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fairportUi.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml $fairportUi.labels | nindent 4 }}
{{- end }}
{{- end }}
