---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-post-delete-cleanup-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-post-delete-cleanup-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "delete", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-post-delete-cleanup-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-post-delete-cleanup-job
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-post-delete-cleanup-job
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-delete-cleanup-job
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-post-delete-cleanup-job
      containers:
      - name: cleanup
        image: ghcr.io/fairport-io/apps/alpine/kubectl:1.34.1 
        command:
        - /bin/sh
        - -c
        - |
          echo "Executing post-delete cleanup..."
          echo "Deleting all Jobs..."
          kubectl delete jobs --all --namespace {{ .Release.Namespace }} --ignore-not-found
          echo "Deleting all PVCs..."
          kubectl delete pvc --all --namespace {{ .Release.Namespace }} --ignore-not-found
          echo "Cleanup complete."
      restartPolicy: Never
  ttlSecondsAfterFinished: 60
