---
fairport-ui:
  enabled: false
  image: ghcr.io/fairport-io/apps/fairport-ui:0.0.1
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000
  serviceAccount:
    create: true
    name: fairport-ui
  env:
    - { name: "PORT", value: "8000" }
    - { name: "APP_NAME", value: "fairport.io" }
  extraEnv: []
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: fairport-ui.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  labels:
    app: fairport-ui
    fairport.io/component: fairport-ui
    fairport.io/name: fairport-ui
