---
name: On Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  on-pull-request:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        
    - name: Check if Author Completed TRAINING.md
      env:
        AUTHOR: ${{ github.event.pull_request.user.login }}
      run: |
        if ! grep -qi "^- $AUTHOR$" .GRADUATES.md; then
            echo "[CRITICAL] PR author ($AUTHOR) not found in .GRADUATES.md"
            echo "[CRITICAL] To fix this please review TRAINING.md"
            echo "[CRITICAL] Exact command: echo \"- $AUTHOR\" >> .GRADUATES.md"
            exit 1
        else
            echo "PR author ($AUTHOR) found in .GRADUATES.md"
        fi

    - name: Build & Test
      run: |
        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        HEAD_SHA="${{ github.event.pull_request.head.sha }}"

        echo "$BASE_SHA" | grep 000000 && echo "[CRITICAL] Invalid SHA $BASE_SHA" && exit 1 

        CHANGED_APPS=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -v '^$' | rev | cut -d '/' -f2- | rev | sort -u)
        
        for D in $CHANGED_APPS; do
            if [ -f "$D/Makefile" ]; then
                [ -z "$D" ] || [ "$D" = "." ] && continue
                echo "[INFO] Selected application: $D"
                
                pushd "$D" > /dev/null
                
                make build || { echo "[CRITICAL] Stage 'build' failed for $D"; exit 1; }
                make test || { echo "[CRITICAL] Stage 'test' failed for $D"; exit 1; }

                popd > /dev/null
            fi
        done
