---
name: On Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  on-pull-request:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if PR author is in GRADUATES.md
      run: |
        AUTHOR="${{ github.event.pull_request.user.login }}"
        if ! grep -qi "^- $AUTHOR$" .GRADUATES.md; then
            echo "[CRITICAL] PR author ($AUTHOR) not found in .GRADUATES.md"
            echo "[CRITICAL] To fix this please review TRAINING.md"
            echo "[CRITICAL] Exact command: echo \"- $AUTHOR\" >> .GRADUATES.md"
            exit 1
        else
            echo "PR author ($AUTHOR) found in .GRADUATES.md"
        fi

    - name: Make Build
      run:
        CHANGED_ROOT_DIRS=$(git diff --name-only origin/${{ github.base_ref }} HEAD | cut -d '/' -f 1 | sort -u)
        for D in $CHANGED_DIRS; do
            if [ -f "$D/Makefile" ]; then
                info "Selected application: $D"
                cd $BASE_DIRECTORY
                cd $D
                make build || crit "Stage: 'build' failed for $D"
                make test || crit "Stage: 'test' failed for $D"
                make deploy || crit "Stage: 'deploy' failed for $D"
            fi
        done
